let places:string[]= ["Germany","japan","Dubai","United States"];
console.log("Original order:", places);
console .log ("Alphabetical order:",[...places].sort());
console .log ("original order:",places);
console .log ("Reverse alphabetical order:",[...places].sort().reverse());
console.log("Original order:",places);
places.reverse();
console.log("Reversed order:",places);
places.reverse();
console.log("original order:",places);
places.sort();
console.log("Alphabetical order:",places);
places.reverse();
console.log("Reverse Alphabetical order:",places);